/**
 * bracketMissions.ts — 100-Level Tier & Level 2 Mission Catalogs.
 * Supports all 12 mission categories:
 * EXPLORATION, SOCIAL, DISCOVERY, ACTIVITY, LANDMARK, CHALLENGE, CHAIN, EVENT, HIDDEN, DAILY, WEEKLY, MILESTONE.
 */

import type { MissionDefinition } from '../MissionTypes';

export const LEVEL_TWO_CHAPTER_TITLE = 'Level 2: The Widening City';

/**
 * Exactly 15 Level 2 Missions covering all 12 categories.
 */
export const LEVEL_TWO_MISSIONS: MissionDefinition[] = [
  {
    id: 'l2_exp_north_traverse',
    title: 'North Quarter Traverse',
    description: 'Explore the northern reaches of RugTown and survey the surrounding monuments.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'exploration',
    difficulty: 'easy',
    minimumLevel: 2,
    objectives: [
      { id: 'visit_whale', kind: 'visit_landmark', targetId: 'whale', label: 'Visit Whale Tower monument' },
      { id: 'walk_north', kind: 'walk_distance', count: 400, label: 'Traverse 400 paces through North District' },
    ],
    rewardXp: 45,
    rewardRep: 8,
    rewardPoints: 25,
    unlocksNext: null,
    district: 'north_quarter',
  },
  {
    id: 'l2_soc_friendly_greeting',
    title: 'Citizen Protocol',
    description: 'Send a wave or greeting to another citizen in the plaza or near Spring Water.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'social',
    difficulty: 'easy',
    minimumLevel: 2,
    objectives: [
      { id: 'use_emote', kind: 'use_emote', label: 'Use a wave or celebratory emote' },
      { id: 'chat_msg', kind: 'send_chat', label: 'Send a welcoming message in city chat' },
    ],
    rewardXp: 50,
    rewardRep: 10,
    rewardPoints: 30,
    unlocksNext: null,
  },
  {
    id: 'l2_disc_secret_pass',
    title: 'Alleyway Whispers',
    description: 'Investigate the secluded alley between Mission HQ and the Quest Archive.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'discovery',
    difficulty: 'medium',
    minimumLevel: 2,
    objectives: [
      { id: 'find_alley', kind: 'interact_landmark', targetId: 'government', label: 'Inspect behind Mission HQ' },
    ],
    rewardXp: 55,
    rewardRep: 12,
    rewardPoints: 35,
    unlocksNext: null,
  },
  {
    id: 'l2_act_distance_runner',
    title: 'City Fitness',
    description: 'Jog through the main promenade and log active movement across RugTown.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'activity',
    difficulty: 'easy',
    minimumLevel: 2,
    objectives: [
      { id: 'walk_distance', kind: 'walk_distance', count: 800, label: 'Log 800 active steps in town' },
    ],
    rewardXp: 40,
    rewardRep: 8,
    rewardPoints: 20,
    unlocksNext: null,
  },
  {
    id: 'l2_land_four_pillars',
    title: 'Pillars of the Plaza',
    description: 'Inspect the four key central landmarks: Fountain, Notice Board, Whale Tower, and Market.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'landmark',
    difficulty: 'medium',
    minimumLevel: 2,
    objectives: [
      { id: 'fountain', kind: 'interact_landmark', targetId: 'fountain', label: 'Inspect Spring Water Fountain' },
      { id: 'notice', kind: 'interact_landmark', targetId: 'notice', label: 'Inspect Central Notice Board' },
      { id: 'whale', kind: 'interact_landmark', targetId: 'whale', label: 'Inspect Whale Tower' },
    ],
    rewardXp: 65,
    rewardRep: 15,
    rewardPoints: 45,
    unlocksNext: null,
  },
  {
    id: 'l2_chal_timed_sprint',
    title: 'The Courier Sprint',
    description: 'Quickly move from Spring Water to the Coffee Shop in one continuous run.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'challenge',
    difficulty: 'medium',
    minimumLevel: 2,
    objectives: [
      { id: 'reach_fountain', kind: 'visit_landmark', targetId: 'fountain', label: 'Start at Spring Water Fountain' },
      { id: 'reach_coffee', kind: 'enter_building', targetId: 'coffee-shop', label: 'Reach Coffee Shop interior' },
    ],
    rewardXp: 60,
    rewardRep: 12,
    rewardPoints: 40,
    unlocksNext: null,
  },
  {
    id: 'l2_chain_informant_part1',
    title: 'The Wire: Stage 1',
    description: 'Meet the underground informant outside Meme Market to begin a multi-step investigation.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'chain',
    difficulty: 'medium',
    minimumLevel: 2,
    objectives: [
      { id: 'talk_informant', kind: 'talk_npc_role', targetId: 'market_trader', label: 'Receive the initial cipher from Pip' },
    ],
    rewardXp: 50,
    rewardRep: 10,
    rewardPoints: 30,
    unlocksNext: 'l2_chain_informant_part2',
  },
  {
    id: 'l2_chain_informant_part2',
    title: 'The Wire: Stage 2',
    description: 'Deliver the decoded cipher to the Mission HQ archives.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'chain',
    difficulty: 'medium',
    minimumLevel: 2,
    objectives: [
      { id: 'visit_hq', kind: 'enter_building', targetId: 'holder-cashback-vault', label: 'Archive the cipher at Quest Archive' },
    ],
    rewardXp: 75,
    rewardRep: 15,
    rewardPoints: 50,
    unlocksNext: null,
  },
  {
    id: 'l2_evt_flash_mob',
    title: 'Plaza Gathering',
    description: 'Join an active city event or gathering in the central plaza.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'event',
    difficulty: 'easy',
    minimumLevel: 2,
    objectives: [
      { id: 'join_event', kind: 'join_city_event', label: 'Participate in any City Event' },
    ],
    rewardXp: 60,
    rewardRep: 12,
    rewardPoints: 35,
    unlocksNext: null,
  },
  {
    id: 'l2_hid_forgotten_bench',
    title: 'The Solitary Rest',
    description: 'Find the quiet bench situated behind the eastern district arches.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'hidden',
    difficulty: 'medium',
    minimumLevel: 2,
    isHidden: true,
    discoveryTrigger: 'LOCATION:east_bench',
    objectives: [
      { id: 'inspect_bench', kind: 'visit_landmark', targetId: 'bench_east', label: 'Discover the secluded bench' },
    ],
    rewardXp: 80,
    rewardRep: 20,
    rewardPoints: 60,
    unlocksNext: null,
  },
  {
    id: 'l2_daily_morning_brew',
    title: 'Daily Cup: Milo Special',
    description: 'Grab your daily morning beverage at the Coffee Shop.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'daily',
    difficulty: 'easy',
    minimumLevel: 2,
    objectives: [
      { id: 'visit_coffee', kind: 'enter_building', targetId: 'coffee-shop', label: 'Step inside Coffee Shop' },
      { id: 'talk_milo', kind: 'talk_npc_role', targetId: 'coffee_worker', label: 'Check in with Milo' },
    ],
    rewardXp: 45,
    rewardRep: 10,
    rewardPoints: 50,
    unlocksNext: null,
  },
  {
    id: 'l2_week_grand_tour',
    title: 'Weekly Circuit: Level 2 Explorer',
    description: 'Visit all 5 primary districts and enter 3 different interiors this week.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'weekly',
    difficulty: 'hard',
    minimumLevel: 2,
    objectives: [
      { id: 'visit_districts', kind: 'visit_any_of', targetIds: ['central', 'north', 'east', 'west', 'south'], count: 4, label: 'Traverse 4 city districts' },
      { id: 'enter_interiors', kind: 'enter_building', count: 3, label: 'Enter 3 public building interiors' },
    ],
    rewardXp: 180,
    rewardRep: 40,
    rewardPoints: 200,
    unlocksNext: null,
  },
  {
    id: 'l2_mile_level_two_graduate',
    title: 'Milestone: Citizen Confirmed',
    description: 'Complete 8 Level 2 missions to solidify your status in RugTown.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'milestone',
    difficulty: 'hard',
    minimumLevel: 2,
    objectives: [
      { id: 'missions_done', kind: 'open_panel', targetId: 'missions', label: 'Achieve Level 2 milestone certification' },
    ],
    rewardXp: 120,
    rewardRep: 30,
    rewardPoints: 100,
    titleUnlockId: 'title_established_citizen',
    unlocksNext: null,
  },
  {
    id: 'l2_act_heartbeat_sync',
    title: 'Active Citizen Beat',
    description: 'Keep moving and maintain continuous activity for 5 minutes in RugTown.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'activity',
    difficulty: 'easy',
    minimumLevel: 2,
    objectives: [
      { id: 'active_movement', kind: 'walk_distance', count: 600, label: 'Sustain active movement in the city' },
    ],
    rewardXp: 50,
    rewardRep: 10,
    rewardPoints: 25,
    unlocksNext: null,
  },
  {
    id: 'l2_soc_community_wave',
    title: 'Citywide Wave',
    description: 'Gather near the Hall of Fame statues and emote alongside other explorers.',
    chapterTitle: LEVEL_TWO_CHAPTER_TITLE,
    category: 'social',
    difficulty: 'medium',
    minimumLevel: 2,
    objectives: [
      { id: 'visit_hall', kind: 'enter_building', targetId: 'hall-of-fame', label: 'Visit the Hall of Fame' },
      { id: 'use_emote', kind: 'use_emote', label: 'Salute the Top 3 champions' },
    ],
    rewardXp: 70,
    rewardRep: 16,
    rewardPoints: 45,
    unlocksNext: null,
  },
];

/**
 * Higher Tier Bracket Highlights (Levels 11 - 100).
 */
export const BRACKET_MISSIONS: MissionDefinition[] = [
  // ── Bracket 2: Explorer (L11-20) ──
  {
    id: 'brk_explorer_survey',
    title: 'The Great City Survey',
    description: 'Map out all 8 perimeter districts and discover every landmark.',
    chapterTitle: 'Tier II: Explorer Odyssey',
    category: 'exploration',
    difficulty: 'medium',
    minimumLevel: 11,
    objectives: [
      { id: 'survey_districts', kind: 'visit_any_of', targetIds: ['north', 'east', 'south', 'west'], count: 4, label: 'Survey all 4 cardinal regions' },
      { id: 'walk_long', kind: 'walk_distance', count: 2000, label: 'Walk 2,000 meters across the metropolis' },
    ],
    rewardXp: 350,
    rewardRep: 75,
    rewardPoints: 150,
    titleUnlockId: 'title_master_explorer',
    unlocksNext: null,
  },

  // ── Bracket 3: Socialite (L21-30) ──
  {
    id: 'brk_socialite_gala',
    title: 'Socialite Gala Access',
    description: 'Engage with 25 distinct citizens and lead a public city event.',
    chapterTitle: 'Tier III: High Society',
    category: 'social',
    difficulty: 'medium',
    minimumLevel: 21,
    objectives: [
      { id: 'meet_citizens', kind: 'meet_player_or_fallback', count: 10, label: 'Interact with 10 players or guild members' },
      { id: 'join_events', kind: 'join_city_event', count: 3, label: 'Participate in 3 City Events' },
    ],
    rewardXp: 600,
    rewardRep: 120,
    rewardPoints: 300,
    titleUnlockId: 'title_town_socialite',
    unlocksNext: null,
  },

  // ── Bracket 4: Specialist (L31-40) ──
  {
    id: 'brk_specialist_alpha_access',
    title: 'Alpha Lounge Clearance',
    description: 'Level 30+ clearance granted. Enter the Alpha Lounge and decode high-tier mission briefings.',
    chapterTitle: 'Tier IV: Specialist Operations',
    category: 'challenge',
    difficulty: 'hard',
    minimumLevel: 31,
    objectives: [
      { id: 'enter_alpha', kind: 'enter_building', targetId: 'alpha-lounge', label: 'Enter Level 30+ Alpha Lounge' },
      { id: 'talk_alpha_lead', kind: 'talk_npc_role', targetId: 'alpha_informant', label: 'Meet the Head Specialist' },
    ],
    rewardXp: 1200,
    rewardRep: 250,
    rewardPoints: 600,
    titleUnlockId: 'title_elite_specialist',
    unlocksNext: null,
  },

  // ── Bracket 5: Investigator (L41-50) ──
  {
    id: 'brk_investigator_archive_secrets',
    title: 'Secrets of the Vault',
    description: 'Crack the Quest Archive vaults and uncover historical city records.',
    chapterTitle: 'Tier V: Grand Investigator',
    category: 'discovery',
    difficulty: 'hard',
    minimumLevel: 41,
    objectives: [
      { id: 'enter_archive', kind: 'enter_building', targetId: 'holder-cashback-vault', label: 'Access Deep Quest Archive' },
      { id: 'hidden_vault', kind: 'interact_landmark', targetId: 'vault_archive', label: 'Inspect the Sealed Codex' },
    ],
    rewardXp: 2500,
    rewardRep: 500,
    rewardPoints: 1200,
    titleUnlockId: 'title_master_investigator',
    unlocksNext: null,
  },

  // ── Bracket 6: Hunter (L51-60) ──
  {
    id: 'brk_hunter_challenge_arena',
    title: 'Arena Trials: Contender',
    description: 'Enter the Challenge Arena and complete the high-speed obstacle and reflex trial.',
    chapterTitle: 'Tier VI: Hunter Crucible',
    category: 'challenge',
    difficulty: 'hard',
    minimumLevel: 51,
    objectives: [
      { id: 'enter_arena', kind: 'enter_building', targetId: 'future-arena', label: 'Enter Challenge Arena' },
      { id: 'arena_trial', kind: 'join_city_event', label: 'Complete Tier VI Arena Trial' },
    ],
    rewardXp: 5000,
    rewardRep: 1000,
    rewardPoints: 2500,
    titleUnlockId: 'title_apex_hunter',
    unlocksNext: null,
  },

  // ── Bracket 7: Elite (L61-70) ──
  {
    id: 'brk_elite_sovereign',
    title: 'The Sovereign Assembly',
    description: 'Convene at Mission HQ and authorize district development orders.',
    chapterTitle: 'Tier VII: RugTown Elite',
    category: 'milestone',
    difficulty: 'hard',
    minimumLevel: 61,
    objectives: [
      { id: 'enter_hq', kind: 'interact_landmark', targetId: 'government', label: 'Preside over Mission HQ council' },
    ],
    rewardXp: 10000,
    rewardRep: 2000,
    rewardPoints: 5000,
    titleUnlockId: 'title_rugtown_elite',
    unlocksNext: null,
  },

  // ── Bracket 8: Master (L71-80) ──
  {
    id: 'brk_master_grand_curator',
    title: 'Curator of the Metropolis',
    description: 'Inspect all monument sites and achieve perfection across all daily challenges.',
    chapterTitle: 'Tier VIII: Grand Master',
    category: 'milestone',
    difficulty: 'hard',
    minimumLevel: 71,
    objectives: [
      { id: 'curator_tour', kind: 'visit_any_of', targetIds: ['fountain', 'whale', 'notice', 'government'], count: 4, label: 'Inspect all 4 sovereign monuments' },
    ],
    rewardXp: 20000,
    rewardRep: 4000,
    rewardPoints: 10000,
    titleUnlockId: 'title_grand_master',
    unlocksNext: null,
  },

  // ── Bracket 9: Legend Hunter (L81-90) ──
  {
    id: 'brk_legend_hunter_trials',
    title: 'The Legend Trials',
    description: 'Master every hidden quest in the city and maintain a 30-day active streak.',
    chapterTitle: 'Tier IX: Legend Hunter',
    category: 'challenge',
    difficulty: 'hard',
    minimumLevel: 81,
    objectives: [
      { id: 'streak_check', kind: 'open_panel', targetId: 'missions', label: 'Verify high-streak consistency status' },
    ],
    rewardXp: 40000,
    rewardRep: 8000,
    rewardPoints: 20000,
    titleUnlockId: 'title_legend_hunter',
    unlocksNext: null,
  },

  // ── Bracket 10: Endgame & The RugTown Legend (L91-100) ──
  {
    id: 'brk_endgame_ascension',
    title: 'The Endgame Citadel',
    description: 'Reach the pinnacle of city exploration and claim your place among the founding pioneers.',
    chapterTitle: 'Tier X: Endgame Pioneer',
    category: 'milestone',
    difficulty: 'hard',
    minimumLevel: 91,
    objectives: [
      { id: 'enter_hall', kind: 'enter_building', targetId: 'hall-of-fame', label: 'Ascend the Hall of Fame podium' },
    ],
    rewardXp: 80000,
    rewardRep: 15000,
    rewardPoints: 40000,
    titleUnlockId: 'title_endgame_pioneer',
    unlocksNext: 'brk_level_100_rugtown_legend',
  },
  {
    id: 'brk_level_100_rugtown_legend',
    title: 'THE RUGTOWN LEGEND',
    description: 'Level 100 reached. The eternal master of RugTown. Your permanent legacy is etched into the city forever.',
    chapterTitle: 'The Eternal Legend',
    category: 'milestone',
    difficulty: 'hard',
    minimumLevel: 100,
    objectives: [
      { id: 'claim_legend', kind: 'interact_landmark', targetId: 'hall-of-fame', label: 'Inscribe your name upon the Eternal Obelisk' },
    ],
    rewardXp: 150000,
    rewardRep: 50000,
    rewardPoints: 100000,
    titleUnlockId: 'title_the_rugtown_legend',
    unlocksNext: null,
  },
];
