import type { MissionDefinition } from '../MissionTypes';

/**
 * Onboarding Chapter One — redesigned first 10 missions.
 * IDs preserved so existing chapter_mission_state / ledger keys stay valid.
 * Rewards rebalanced for slower early levelling (total ~320 XP).
 */
export const ONBOARDING_CHAPTER_TITLE = 'Chapter One: Citizen of RugTown';

export const STARTER_MISSIONS: MissionDefinition[] = [
  {
    id: 'ch1_new_face',
    title: 'Welcome to RugTown',
    description: 'Find your footing. Reach Spring Water and interact with the fountain.',
    chapterTitle: ONBOARDING_CHAPTER_TITLE,
    category: 'onboarding',
    difficulty: 'easy',
    objectives: [
      { id: 'reach_fountain', kind: 'visit_landmark', targetId: 'fountain', label: 'Reach Spring Water' },
      { id: 'use_fountain', kind: 'interact_landmark', targetId: 'fountain', label: 'Interact with the fountain' },
    ],
    objectiveHint: 'Walk to Spring Water and press E.',
    rewardXp: 15,
    rewardRep: 2,
    unlocksNext: 'ch1_water_before_rumours',
    buildingDestination: 'fountain',
  },
  {
    id: 'ch1_water_before_rumours',
    title: 'Meet the Guide',
    description: 'Talk to the Town Crier and open your mission list.',
    chapterTitle: ONBOARDING_CHAPTER_TITLE,
    category: 'onboarding',
    difficulty: 'easy',
    objectives: [
      { id: 'talk_guide', kind: 'talk_town_crier', label: 'Talk to the Town Crier' },
      { id: 'open_missions', kind: 'open_panel', targetId: 'missions', label: 'Open the mission panel' },
    ],
    objectiveHint: 'Find the Town Crier, then open Missions from the HUD.',
    rewardXp: 20,
    rewardRep: 3,
    unlocksNext: 'ch1_empty_cart',
    npcDestination: 'town_crier',
  },
  {
    id: 'ch1_empty_cart',
    title: 'Find Your Look',
    description: 'Open the character creator and save an appearance.',
    chapterTitle: ONBOARDING_CHAPTER_TITLE,
    category: 'onboarding',
    difficulty: 'easy',
    objectives: [
      { id: 'open_creator', kind: 'open_panel', targetId: 'character', label: 'Open character creator' },
      { id: 'save_look', kind: 'customize_character', label: 'Save your appearance' },
    ],
    objectiveHint: 'Open Character / Outfit and confirm your look.',
    rewardXp: 25,
    rewardRep: 4,
    achievementProgressId: 'ach_customize_character',
    unlocksNext: 'ch1_milo_heard',
  },
  {
    id: 'ch1_milo_heard',
    title: 'The Notice Board',
    description: 'Visit the Notice Board and accept a posted mission lead.',
    chapterTitle: ONBOARDING_CHAPTER_TITLE,
    category: 'onboarding',
    difficulty: 'easy',
    objectives: [
      { id: 'visit_notice', kind: 'visit_landmark', targetId: 'notice', label: 'Visit the Notice Board' },
      { id: 'accept_lead', kind: 'accept_mission', label: 'Inspect / accept a mission lead' },
    ],
    objectiveHint: 'Press E at the Notice Board and pin a lead.',
    rewardXp: 25,
    rewardRep: 4,
    unlocksNext: 'ch1_notice_never_posted',
    buildingDestination: 'notice',
  },
  {
    id: 'ch1_notice_never_posted',
    title: 'Coffee and Conversation',
    description: 'Visit the Coffee Shop and talk to the barista.',
    chapterTitle: ONBOARDING_CHAPTER_TITLE,
    category: 'onboarding',
    difficulty: 'easy',
    objectives: [
      { id: 'enter_coffee', kind: 'enter_building', targetId: 'coffee-shop', label: 'Enter the Coffee Shop' },
      { id: 'talk_barista', kind: 'talk_npc_role', targetId: 'coffee_worker', label: 'Talk to the Coffee Shop worker' },
    ],
    objectiveHint: 'Enter the Coffee Shop and talk to Milo.',
    rewardXp: 30,
    rewardRep: 5,
    unlocksNext: 'ch1_proof_not_panic',
    buildingDestination: 'coffee',
    npcDestination: 'coffee_worker',
  },
  {
    id: 'ch1_proof_not_panic',
    title: 'Market Watch',
    description: 'Visit Meme Market and learn how city events work.',
    chapterTitle: ONBOARDING_CHAPTER_TITLE,
    category: 'onboarding',
    difficulty: 'medium',
    objectives: [
      { id: 'enter_market', kind: 'enter_building', targetId: 'meme-market', label: 'Enter Meme Market' },
      { id: 'talk_trader', kind: 'talk_npc_role', targetId: 'market_trader', label: 'Talk to the market trader' },
      { id: 'learn_events', kind: 'open_panel', targetId: 'events', label: 'Open city events' },
    ],
    objectiveHint: 'Enter Meme Market, talk to Pip, then open Events.',
    rewardXp: 30,
    rewardRep: 5,
    unlocksNext: 'ch1_patterns_in_ink',
    buildingDestination: 'market',
    npcDestination: 'market_trader',
  },
  {
    id: 'ch1_patterns_in_ink',
    title: 'Say Hello',
    description: 'Send a city chat, use an emote, and greet another player (or an NPC if the city is quiet).',
    chapterTitle: ONBOARDING_CHAPTER_TITLE,
    category: 'social',
    difficulty: 'medium',
    objectives: [
      { id: 'chat', kind: 'send_chat', label: 'Send one city chat message' },
      { id: 'emote', kind: 'use_emote', label: 'Use one emote' },
      { id: 'meet', kind: 'meet_player_or_fallback', label: 'Meet a player or talk to a citizen' },
    ],
    objectiveHint: 'Use chat + emote, then greet someone nearby.',
    rewardXp: 35,
    rewardRep: 6,
    unlocksNext: 'ch1_bridge_keeps_count',
  },
  {
    id: 'ch1_bridge_keeps_count',
    title: 'Rumours in the City',
    description: 'Join a city event and perform the required interaction at its location.',
    chapterTitle: ONBOARDING_CHAPTER_TITLE,
    category: 'city_event',
    difficulty: 'medium',
    objectives: [
      { id: 'join_event', kind: 'join_city_event', label: 'Participate in one city event' },
    ],
    objectiveHint: 'Wait for a city event banner, travel there, and interact.',
    rewardXp: 40,
    rewardRep: 7,
    achievementProgressId: 'ach_first_city_event',
    unlocksNext: 'ch1_whales_shadow',
  },
  {
    id: 'ch1_whales_shadow',
    title: 'Form a Crew',
    description: 'Create or join a party and complete one shared party action (solo practice allowed when alone).',
    chapterTitle: ONBOARDING_CHAPTER_TITLE,
    category: 'party',
    difficulty: 'medium',
    objectives: [
      { id: 'party', kind: 'party_or_solo_action', label: 'Open Party and complete a crew action' },
    ],
    objectiveHint: 'Open the Party panel and start or practice a shared action.',
    rewardXp: 40,
    rewardRep: 7,
    unlocksNext: 'ch1_missing_ledger',
  },
  {
    id: 'ch1_missing_ledger',
    title: 'Citizen of RugTown',
    description: 'Tour key districts, then return to the Town Crier to claim your citizenship.',
    chapterTitle: ONBOARDING_CHAPTER_TITLE,
    category: 'onboarding',
    difficulty: 'hard',
    objectives: [
      {
        id: 'tour',
        kind: 'visit_any_of',
        targetIds: ['government', 'trading_academy', 'bridge', 'whale', 'fame'],
        count: 3,
        label: 'Visit 3 major landmarks',
      },
      { id: 'return_crier', kind: 'talk_town_crier', label: 'Return to the Town Crier' },
    ],
    objectiveHint: 'Visit three landmarks, then speak with the Town Crier.',
    rewardXp: 60,
    rewardRep: 12,
    titleUnlockId: 'title_new_citizen',
    achievementProgressId: 'ach_onboarding_complete',
    unlocksNext: null,
    npcDestination: 'town_crier',
  },
];

/** Total onboarding XP (for pacing comments / tests). */
export const STARTER_MISSIONS_TOTAL_XP = STARTER_MISSIONS.reduce((s, m) => s + m.rewardXp, 0);
