import type { MissionDefinition } from '../MissionTypes';

export const STORY_CHAPTER_TITLE = 'Chapter Two: City Threads';

/**
 * Five multi-stage story arcs (sequential stages as linked missions).
 * Unlocked after onboarding finale. Server XP/REP via additive story RPCs
 * when migration is applied; guests track locally.
 */
export const STORY_MISSIONS: MissionDefinition[] = [
  /* ── Arc 1: The Missing Market Ledger ── */
  {
    id: 'story_ledger_talk',
    title: 'The Missing Market Ledger',
    description: 'Pip at Meme Market swears the daily ledger walked off.',
    chapterTitle: STORY_CHAPTER_TITLE,
    category: 'story',
    difficulty: 'medium',
    objectives: [{ id: 'talk', kind: 'talk_npc_role', targetId: 'market_trader', label: 'Talk to the market trader' }],
    objectiveHint: 'Enter Meme Market and talk to Pip.',
    rewardXp: 35,
    rewardRep: 6,
    unlocksNext: 'story_ledger_office',
    buildingDestination: 'market',
  },
  {
    id: 'story_ledger_office',
    title: 'Books at the Office',
    description: 'Check the Financial Office for a paper trail.',
    chapterTitle: STORY_CHAPTER_TITLE,
    category: 'story',
    difficulty: 'medium',
    objectives: [{ id: 'visit', kind: 'interact_landmark', targetId: 'financial_office', label: 'Inspect Financial Office' }],
    rewardXp: 40,
    rewardRep: 7,
    unlocksNext: 'story_ledger_bank',
    buildingDestination: 'financial_office',
  },
  {
    id: 'story_ledger_bank',
    title: 'Holder Bank Cross-Check',
    description: 'Compare notes at Holder Bank.',
    chapterTitle: STORY_CHAPTER_TITLE,
    category: 'story',
    difficulty: 'medium',
    objectives: [{ id: 'visit', kind: 'interact_landmark', targetId: 'holder_bank', label: 'Inspect Holder Bank' }],
    rewardXp: 40,
    rewardRep: 7,
    unlocksNext: 'story_ledger_return',
    buildingDestination: 'holder_bank',
  },
  {
    id: 'story_ledger_return',
    title: 'Ledger Reported',
    description: 'Return to Pip with what you found.',
    chapterTitle: STORY_CHAPTER_TITLE,
    category: 'story',
    difficulty: 'medium',
    objectives: [{ id: 'talk', kind: 'talk_npc_role', targetId: 'market_trader', label: 'Report back to Pip' }],
    rewardXp: 55,
    rewardRep: 10,
    unlocksNext: 'story_whale_rumour',
    buildingDestination: 'market',
  },

  /* ── Arc 2: Rumours from Whale Tower ── */
  {
    id: 'story_whale_rumour',
    title: 'Rumours from Whale Tower',
    description: 'An Alpha Lounge informant has a tip about Whale Tower.',
    chapterTitle: STORY_CHAPTER_TITLE,
    category: 'story',
    difficulty: 'medium',
    objectives: [{ id: 'talk', kind: 'talk_npc_role', targetId: 'alpha_informant', label: 'Talk to the Alpha informant' }],
    rewardXp: 35,
    rewardRep: 6,
    unlocksNext: 'story_whale_visit',
    buildingDestination: 'alpha',
  },
  {
    id: 'story_whale_visit',
    title: 'Tower Watch',
    description: 'Inspect Whale Tower and catch an event signal.',
    chapterTitle: STORY_CHAPTER_TITLE,
    category: 'story',
    difficulty: 'medium',
    objectives: [
      { id: 'whale', kind: 'interact_landmark', targetId: 'whale', label: 'Inspect Whale Tower' },
      { id: 'event', kind: 'join_city_event', label: 'Join a related city event' },
    ],
    rewardXp: 50,
    rewardRep: 8,
    unlocksNext: 'story_whale_report',
    buildingDestination: 'whale',
  },
  {
    id: 'story_whale_report',
    title: 'Report to Alpha',
    description: 'Bring the rumour confirmation back to Alpha Lounge.',
    chapterTitle: STORY_CHAPTER_TITLE,
    category: 'story',
    difficulty: 'medium',
    objectives: [{ id: 'talk', kind: 'talk_npc_role', targetId: 'alpha_informant', label: 'Report to the informant' }],
    rewardXp: 55,
    rewardRep: 10,
    unlocksNext: 'story_vault_investigate',
    buildingDestination: 'alpha',
  },

  /* ── Arc 3: The Locked Cashback Vault ── */
  {
    id: 'story_vault_investigate',
    title: 'The Locked Cashback Vault',
    description: 'The vault is sealed — gather clues without forcing the door.',
    chapterTitle: STORY_CHAPTER_TITLE,
    category: 'story',
    difficulty: 'hard',
    objectives: [{ id: 'vault', kind: 'interact_landmark', targetId: 'cashback', label: 'Inspect the locked vault' }],
    rewardXp: 30,
    rewardRep: 5,
    unlocksNext: 'story_vault_clues',
    buildingDestination: 'cashback',
  },
  {
    id: 'story_vault_clues',
    title: 'Vault Clues',
    description: 'Ask around Government Quarter and Trading Academy.',
    chapterTitle: STORY_CHAPTER_TITLE,
    category: 'story',
    difficulty: 'hard',
    objectives: [
      { id: 'gov', kind: 'interact_landmark', targetId: 'government', label: 'Visit Government Quarter' },
      { id: 'academy', kind: 'interact_landmark', targetId: 'trading_academy', label: 'Visit Trading Academy' },
    ],
    rewardXp: 45,
    rewardRep: 8,
    unlocksNext: 'story_vault_report',
  },
  {
    id: 'story_vault_report',
    title: 'Vault Remains Sealed',
    description: 'Report findings — the vault stays locked by design.',
    chapterTitle: STORY_CHAPTER_TITLE,
    category: 'story',
    difficulty: 'hard',
    objectives: [{ id: 'talk', kind: 'talk_npc_role', targetId: 'government_official', label: 'Report to the civic official' }],
    rewardXp: 50,
    rewardRep: 9,
    unlocksNext: 'story_fame_tasks',
    buildingDestination: 'government',
  },

  /* ── Arc 4: Hall of Fame Candidate ── */
  {
    id: 'story_fame_tasks',
    title: 'Hall of Fame Candidate',
    description: 'Prove your city standing before inspecting the Hall.',
    chapterTitle: STORY_CHAPTER_TITLE,
    category: 'story',
    difficulty: 'hard',
    objectives: [
      { id: 'events', kind: 'join_city_event', count: 1, label: 'Complete a city event' },
      { id: 'chat', kind: 'send_chat', label: 'Send a city chat' },
    ],
    rewardXp: 40,
    rewardRep: 8,
    unlocksNext: 'story_fame_visit',
  },
  {
    id: 'story_fame_visit',
    title: 'Hall Inspection',
    description: 'Visit Hall of Fame and review the plaques.',
    chapterTitle: STORY_CHAPTER_TITLE,
    category: 'story',
    difficulty: 'medium',
    objectives: [
      { id: 'enter', kind: 'enter_building', targetId: 'hall-of-fame', label: 'Enter Hall of Fame' },
      { id: 'interact', kind: 'interact_landmark', targetId: 'fame', label: 'Inspect the Hall exhibits' },
    ],
    rewardXp: 55,
    rewardRep: 10,
    achievementProgressId: 'ach_hall_candidate',
    unlocksNext: 'story_arena_prep',
    buildingDestination: 'fame',
  },

  /* ── Arc 5: Arena Preparations ── */
  {
    id: 'story_arena_prep',
    title: 'Arena Preparations',
    description: 'Visit the Arena and Tournament Hall, then speak with the coordinator.',
    chapterTitle: STORY_CHAPTER_TITLE,
    category: 'story',
    difficulty: 'hard',
    objectives: [
      { id: 'arena', kind: 'interact_landmark', targetId: 'arena', label: 'Inspect the Arena' },
      { id: 'hall', kind: 'interact_landmark', targetId: 'tournament_hall', label: 'Visit Tournament Hall' },
      { id: 'talk', kind: 'talk_npc_role', targetId: 'arena_coordinator', label: 'Talk to the Arena coordinator' },
    ],
    rewardXp: 70,
    rewardRep: 12,
    unlocksNext: null,
    buildingDestination: 'arena',
    npcDestination: 'arena_coordinator',
  },
];
